name = "temp-mail"
main = "src/index.js"
compatibility_date = "2024-02-22"

[[d1_databases]]
binding = "DB"
database_name = "temp-mail-db"
database_id = "626e067b-eb1e-4a87-b7cd-33a2faf3308c" 

[[email.bindings]]
name = "EMAIL_ROUTING"
